name: password_manager
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  local_auth: ^2.1.6
  flutter:
    sdk: flutter
  flutter_speed_dial: ^7.0.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  intl_phone_field: ^3.2.0
  http: ^1.4.0
  crypto: ^3.0.6
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  path_provider: ^2.1.5
  hive: ^2.2.3
  cryptography: ^2.7.0
  icons_plus: ^5.0.0
  connectivity_plus: ^6.1.4
  share_plus: ^11.0.0
  file_picker: ^10.2.0
  qr_flutter: ^4.0.0
  otp: ^3.0.1
  base32: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  dependency_validator: ^3.0.0
flutter:
  assets:
    - assets/card.png
    - assets/no_items.png
  uses-material-design: true
